# Odra configuration file for DEX smart contracts

# Flipper example contract
[[contracts]]
fqn = "flipper::Flipper"

# LP Token contract
[[contracts]]
fqn = "token::LpToken"

# DEX Pair contract
[[contracts]]
fqn = "dex::pair::Pair"

# DEX Pair Factory contract
[[contracts]]
fqn = "dex::pair::PairFactory"

# DEX Factory contract
[[contracts]]
fqn = "dex::factory::Factory"

# DEX Router contract
[[contracts]]
fqn = "dex::router::Router"

# ECTO Token contract
[[contracts]]
fqn = "tokens::EctoToken"

# USDC Token contract
[[contracts]]
fqn = "tokens::UsdcToken"

# WETH Token contract
[[contracts]]
fqn = "tokens::WethToken"

# WBTC Token contract
[[contracts]]
fqn = "tokens::WbtcToken"

# Launchpad Token Factory contract
[[contracts]]
fqn = "launchpad::token_factory::TokenFactory"

# Launchpad Launch Token contract
[[contracts]]
fqn = "launchpad::launch_token::LaunchToken"

# Launchpad Bonding Curve contract
[[contracts]]
fqn = "launchpad::bonding_curve::BondingCurve"
